# Configuração da conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ultrav?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
# Coloque a sua senha do MySQL na linha abaixo
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'update' faz o Hibernate ajustar as tabelas se necessário sem apagar seus dados inseridos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o aviso do Open In View (opcional, limpa o log)
spring.jpa.open-in-view=false
